### ISSUE TITLE
Generalize name of Parallel typeclass 

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-parallel#15] opened 2016-10-26 13:50 UTC
After reading this [reddit thread](https://www.reddit.com/r/haskell/comments/53a0kq/abstracting_asyncconcurrently/) i'm thinking that name `Parallel` or `Concurent` is not that precise as this typeclass is just pearing/isomorphism between some Monad and some Applicative.

This are example are not strictly related to concurrency/parallelism:
- List Monad and ZipList Applicative
- Either Monad  and Validation Applicative

For now I don't have a better name but will think on this.

Related [fantasy-land#186](https://github.com/fantasyland/fantasy-land/issues/186)

**Comment by garyb** [comment] 2016-10-26 13:57
It's true it is more widely applicable, but `Parallel` is the intent for it since it's attempting to capture `Monad`/`Applicative` relationships where the behaviour of the `Applicative` differs from that of the `Monad` so as to enable parallelism.

As an example, see here:

https://github.com/purescript/purescript-transformers/pull/77#issuecomment-252689250

(The issue is now fixed, but if you use `parallel` with `MaybeT` or `EitherT` it behaves as in the example there, where the effects occur regardless of failure).

Soo, I'm not sure what to suggest. There almost certainly is a more accurate description for what this class represents, but only if you ignore the operational semantics.

**Comment by safareli** [comment] 2016-10-26 14:37
Yes but going from `Either` to `Validation` using `parallel` sounds weird, but going from `Validation` to `Either` using `sequential` lgtm as "sequential" captures behavior of Monads in general.

If we have some word which captures behavior of Applicatives for example "static".
Difference between Monad and Applicative is that with applicative we have whole computation statically available but Monads are more powerful and program written using Monads can not be observed statically i.e. is dynamic so if we somehow express that, then we would have much general name/words for the typeclass:
```hs
class (Monad m, Applicative f) <= _______ f m | m -> f, f -> m where
  static  :: m ~> f
  dynamic :: f ~> m
```

Or maybe if we look at monad and applicative as strong and weak then: 
```hs
class (Monad m, Applicative f) <= Strength f m | m -> f, f -> m where
  weaken     :: m ~> f
  strengthen :: f ~> m
```

this wording is not best but gives idea of what i'm thinking on.

**Comment by hdgarrood** [comment] 2020-05-21 01:53
I think "parallel" and "sequential" make sense; as you say, "sequential" is kind of intrinsic to monads, and "parallel" is the natural opposite of "sequential". In any case, neither `static`/`dynamic` nor `weaken`/`strengthen` seem to have generated much interest, and this issue has been open for a very long time, so I vote to close.

**Closed** 2020-05-25 18:25 UTC
